
Maci\MailerBundle\Entity\Mail:
    type:  entity
    table: maci_mailer_mail
    repositoryClass: Maci\MailerBundle\Repository\MailRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 127
        template:
            type: string
            length: 63
            nullable: true
        token:
            type: string
            length: 127
        to:
            type: array
            nullable: true
        header:
            type: string
            length: 63
            nullable: true
        index:
            type: smallint
        from:
            type: string
            length: 63
            nullable: true
        bcc:
            type: string
            length: 63
            nullable: true
        type:
            type: string
            length: 31
            nullable: true
        subject:
            type: string
            length: 127
        text:
            type: text
            nullable: true
        content:
            type: text
            nullable: true
        locale:
            type: string
            length: 10
        public:
            type: boolean
        created:
            type: datetime
        updated:
            type: datetime
        removed:
            type: boolean
    manyToOne:
        user:
            targetEntity: Maci\UserBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [ setUpdatedValue, setCreatedValue ]
        preUpdate: [ setUpdatedValue ]
