
Maci\MailerBundle\Entity\Newsletter:
    type:  entity
    table: maci_mailer_newsletter
    # repositoryClass: Maci\MailerBundle\Repository\NewsletterRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        token:
            type: string
            length: 15
        subject:
            type: string
            length: 63
        text:
            type: text
        html:
            type: text
            nullable: true
        private:
            type: boolean
        data:
            type: json
