<?php

namespace Maci\MailerBundle\Repository;

/**
 * SubscriberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriberRepository extends \Doctrine\ORM\EntityRepository
{
    public function getList()
    {
        $q = $this->getEntityManager()
            ->createQuery(
                'SELECT s FROM MaciMailerBundle:Subscriber s WHERE s.removed = false ORDER BY s.created DESC'
            )
        ;

        return $q->getResult();
    }
}
